name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@b84ea111af0e1eacc43da3fdf55b403e4258eb2b  # v0.80.25
